package provider_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccCustomGroupResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             checkDestroyByID(t, "CustomGroup", "civicrm_custom_group"),
		Steps: []resource.TestStep{
			// Create with an explicit table_name; verify it is stored in the DB.
			{
				Config: providerConfig() + `
resource "civicrm_custom_group" "test" {
  name       = "tf_acc_cg"
  title      = "TF Acceptance Custom Group"
  extends    = "Contact"
  table_name = "civicrm_value_tf_acc_cg"
}`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("civicrm_custom_group.test", "id"),
					resource.TestCheckResourceAttr("civicrm_custom_group.test", "name", "tf_acc_cg"),
					resource.TestCheckResourceAttr("civicrm_custom_group.test", "title", "TF Acceptance Custom Group"),
					resource.TestCheckResourceAttr("civicrm_custom_group.test", "extends", "Contact"),
					resource.TestCheckResourceAttr("civicrm_custom_group.test", "is_active", "true"),
					resource.TestCheckResourceAttr("civicrm_custom_group.test", "table_name", "civicrm_value_tf_acc_cg"),
					// DB verification
					checkEntityAttr(t, "CustomGroup", "civicrm_custom_group.test", "id", "title", "TF Acceptance Custom Group"),
					checkEntityAttr(t, "CustomGroup", "civicrm_custom_group.test", "id", "table_name", "civicrm_value_tf_acc_cg"),
				),
			},
			// Import
			{
				ResourceName:      "civicrm_custom_group.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update title; table_name must stay unchanged in the DB (write-once via UseStateForUnknown).
			{
				Config: providerConfig() + `
resource "civicrm_custom_group" "test" {
  name       = "tf_acc_cg"
  title      = "TF Acceptance Custom Group Updated"
  extends    = "Contact"
  table_name = "civicrm_value_tf_acc_cg"
}`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("civicrm_custom_group.test", "title", "TF Acceptance Custom Group Updated"),
					// DB: title changed, table_name untouched
					checkEntityAttr(t, "CustomGroup", "civicrm_custom_group.test", "id", "title", "TF Acceptance Custom Group Updated"),
					checkEntityAttr(t, "CustomGroup", "civicrm_custom_group.test", "id", "table_name", "civicrm_value_tf_acc_cg"),
				),
			},
		},
	})
}

// TestAccCustomGroupResourceAutoTableName verifies that when table_name is
// omitted from config, CiviCRM generates it on create and Terraform preserves
// the generated value on subsequent applies (UseStateForUnknown behaviour).
func TestAccCustomGroupResourceAutoTableName(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             checkDestroyByID(t, "CustomGroup", "civicrm_custom_group"),
		Steps: []resource.TestStep{
			// Create without table_name; the provider must receive and store the generated name.
			{
				Config: providerConfig() + `
resource "civicrm_custom_group" "auto" {
  name    = "tf_acc_cg_auto"
  title   = "TF Acceptance Auto Table Name"
  extends = "Contact"
}`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("civicrm_custom_group.auto", "id"),
					// table_name must be non-empty after create (auto-generated by CiviCRM)
					resource.TestCheckResourceAttrSet("civicrm_custom_group.auto", "table_name"),
					// DB must have the same auto-generated table name as Terraform state
					checkEntityAttr(t, "CustomGroup", "civicrm_custom_group.auto", "id", "name", "tf_acc_cg_auto"),
				),
			},
			// Update title only; table_name must remain unchanged (not nulled out or regenerated).
			{
				Config: providerConfig() + `
resource "civicrm_custom_group" "auto" {
  name    = "tf_acc_cg_auto"
  title   = "TF Acceptance Auto Table Name Updated"
  extends = "Contact"
}`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("civicrm_custom_group.auto", "title", "TF Acceptance Auto Table Name Updated"),
					// table_name still set and stable
					resource.TestCheckResourceAttrSet("civicrm_custom_group.auto", "table_name"),
					checkEntityAttr(t, "CustomGroup", "civicrm_custom_group.auto", "id", "title", "TF Acceptance Auto Table Name Updated"),
				),
			},
		},
	})
}
